name: Terraform Plan Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev   # yahi se terraform commands chalenge

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init \
          -backend-config="testrg=${{ secrets.AZURE_RG }}" \
          -backend-config="testsg=${{ secrets.AZURE_STORAGE }}" \
          -backend-config="tfstate=${{ secrets.AZURE_CONTAINER }}" \
          -backend-config="key=dev.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
