name: Terraform Plan Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev   # Terraform code yaha hai

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Azure Login using Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # Terraform Init with Azure backend (hardcoded values)
      - name: Terraform Init
        run: terraform init \
          -backend-config="resource_group_name=testrg" \
          -backend-config="storage_account_name=testsg" \
          -backend-config="container_name=tfstate" \
          -backend-config="key=dev.tfstate"

      # Validate code
      - name: Terraform Validate
        run: terraform validate

      # Plan only
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Upload Plan file as artifact (optional)
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: environments/dev/tfplan
